export {default as Home} from './Home';
export { default as Login} from './Login';
export {default as Signup} from './Signup';
export {default as Communities} from './Communities';
export{default as Events} from './Events';
export {default as Rsvp} from './Rsvp';
export{default as Forgotpwd} from './Forgotpwd';
export{default as Joinus} from './Joinus';
export {default as Dashboard} from './Dashboard';
export {default as Createvents} from './Createvents';